'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Events', 
      [
        {
          eventName: "Football Game",
          eventLocation: "London",
          eventDescription: "Relaxed football game - all abilities welcome. We'll probably go to the pub afterwards!",
          skillLevel: "All Levels",
          CategoryId: 21,
          equipNeeded: "0",
          eventPrice: 5,
          eventDate: "2024-09-23",
          eventTime: "19:00",
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          eventName: "Running Club",
          eventLocation: "London",
          eventDescription: "A group that gets together weekly to train for upcoming races.",
          skillLevel: "Intermediate",
          CategoryId: 21,
          equipNeeded: "1",
          eventPrice: 0,
          eventDate: "2024-09-17",
          eventTime: "18:00",
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          eventName: "Hockey League",
          eventLocation: "Manchester",
          eventDescription: "Get involved in our relaxed hockey league - join as an established team or come solo and we will place you.",
          skillLevel: "Beginners",
          CategoryId: 21,
          equipNeeded: "1",
          eventPrice: 15,
          eventDate: "2024-09-29",
          eventTime: "15:00",
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          eventName: "Bouldering Group",
          eventLocation: "Cardiff",
          eventDescription: "Relaxed climbing session - we can work on our problems together or go solo. Shoes and chalk provided.",
          skillLevel: "All Levels",
          CategoryId: 22,
          equipNeeded: "0",
          eventPrice: 10,
          eventDate: "2024-09-20",
          eventTime: "17:00",
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          eventName: "Cookery Class",
          eventLocation: "Cardiff",
          eventDescription: "Learn how to cook Italian culinary classics in a relaxed, welcoming environment.",
          skillLevel: "Beginners",
          CategoryId: 23,
          equipNeeded: "0",
          eventPrice: 20,
          eventDate: "2024-10-05",
          eventTime: "14:00",
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          eventName: "Chocolate-making Course",
          eventLocation: "Cardiff",
          eventDescription: "Ever wondered how chocolate was made? Join our day-long course to learn all things chocolate and become a skilled chocolatier.",
          skillLevel: "All Levels",
          CategoryId: 23,
          equipNeeded: "0",
          eventPrice: 45,
          eventDate: "2024-10-01",
          eventTime: "09:00",
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          eventName: "Guitar Lesson",
          eventLocation: "Manchester",
          eventDescription: "Guitar lessons for total beginners - group lessons that take place weekly",
          skillLevel: "Beginners",
          CategoryId: 24,
          equipNeeded: "0",
          eventPrice: 12,
          eventDate: "2024-10-15",
          eventTime: "18:00",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
       
        {
          eventName: "Open-mic Night",
          eventLocation: "London",
          eventDescription: "Relaxed open-mic night for all musicians to play and/or watch. Performers get one free drink.",
          skillLevel: "Intermediate",
          CategoryId: 24,
          equipNeeded: "1",
          eventPrice: 0,
          eventDate: "2024-10-07",
          eventTime: "20:00",
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          eventName: "Gig Group",
          eventLocation: "London",
          eventDescription: "Want to go to gigs but have no one to go with? Join our community of music lovers to meet new friends and enjoy music together. We meet up every month to learn more about each other and get a sense for the different tastes we have, so we can plan gigs from there.",
          skillLevel: "All Levels",
          CategoryId: 24,
          equipNeeded: "0",
          eventPrice: 0,
          eventDate: "2024-11-07",
          eventTime: "19:00",
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          eventName: "Chess Club",
          eventLocation: "Cardiff",
          eventDescription: "Open sessions at the local chess club that happen on week-nights, come to play, improve your skill and meet new people",
          skillLevel: "All Levels",
          CategoryId: 25,
          equipNeeded: "0",
          eventPrice: 0,
          eventDate: "2024-10-09",
          eventTime: "19:00",
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          eventName: "D&D Campaign",
          eventLocation: "Manchester",
          eventDescription: "New Dungeons and Dragons campaigns hosted by the Cardiff D&D society - bring your pre-made characters and dice.",
          skillLevel: "Intermediate",
          CategoryId: 25,
          equipNeeded: "1",
          eventPrice: 3,
          eventDate: "2024-10-13",
          eventTime: "17:00",
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          eventName: "Fortnite Group",
          eventLocation: "London",
          eventDescription: "Play fortnite with new friends",
          skillLevel: "All Levels",
          CategoryId: 25,
          equipNeeded: "1",
          eventPrice: 0,
          eventDate: "2024-09-25",
          eventTime: "19:00",
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          eventName: "Knitting and Cake",
          eventLocation: "Manchester",
          eventDescription: "Come and join this knitting group at the Green cafe - £3 to eat as much cake as possible while working on your own projects and chatting.",
          skillLevel: "All Levels",
          CategoryId: 26,
          equipNeeded: "1",
          eventPrice: 3,
          eventDate: "2024-09-15",
          eventTime: "16:00",
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          eventName: "Pottery Class",
          eventLocation: "Cardiff",
          eventDescription: "Learn how to make your own pottery - mugs, planters, tableware, or anything your creativity can create",
          skillLevel: "All Levels",
          CategoryId: 26,
          equipNeeded: "0",
          eventPrice: 10,
          eventDate: "2024-10-02",
          eventTime: "17:00",
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          eventName: "Paint and Wine",
          eventLocation: "London",
          eventDescription: "Let your creativity flow with a bottle of Merlot.",
          skillLevel: "All Levels",
          CategoryId: 26,
          equipNeeded: "0",
          eventPrice: 15,
          eventDate: "2024-10-04",
          eventTime: "20:00",
          createdAt: new Date(),
          updatedAt: new Date(),
        },


        {
          eventName: "Soup Kitchen",
          eventLocation: "Cardiff",
          eventDescription: "Come and volunteer at our weekly soup kitchen, providing meals for those who attend. Safety training provided.",
          skillLevel: "All Levels",
          CategoryId: 27,
          equipNeeded: "0",
          eventPrice: 0,
          eventDate: "2024-10-11",
          eventTime: "16:00",
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          eventName: "Dog Shelter Volunteering",
          eventLocation: "Manchester",
          eventDescription: "Local dog shelter looking for volunteers to help with dog-care, including walking, feeding, playing and cleaning out pens.",
          skillLevel: "All Levels",
          CategoryId: 27,
          equipNeeded: "0",
          eventPrice: 0,
          eventDate: "2024-11-01",
          eventTime: "10:00",
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          eventName: "Community Garden",
          eventLocation: "London",
          eventDescription: "No previous gardening skills needed - come help us care for our crops and plant vegetables.",
          skillLevel: "All Levels",
          CategoryId: 27,
          equipNeeded: "0",
          eventPrice: 0,
          eventDate: "2024-11-06",
          eventTime: "14:00",
          createdAt: new Date(),
          updatedAt: new Date(),
        },


        {
          eventName: "Movie Club",
          eventLocation: "Cardiff",
          eventDescription: "Think book club, but with movies! Every week we choose a movie to watch and then meet up to discuss with snacks and drinks.",
          skillLevel: "All Levels",
          CategoryId: 28,
          equipNeeded: "0",
          eventPrice: 2,
          eventDate: "2024-11-06",
          eventTime: "21:30",
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          eventName: "Trekkie Drinks",
          eventLocation: "Manchester",
          eventDescription: "A chance for all Manchester-based trekkies to meet up over good food and discuss the final frontier and anything else.",
          skillLevel: "All Levels",
          CategoryId: 28,
          equipNeeded: "0",
          eventPrice: 0,
          eventDate: "2024-11-12",
          eventTime: "21:00",
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          eventName: "Local Film Festival",
          eventLocation: "Manchester",
          eventDescription: "Locally-organised film festival showing new releases and forgotten gems.",
          skillLevel: "All Levels",
          CategoryId: 28,
          equipNeeded: "0",
          eventPrice: 11,
          eventDate: "2024-11-30",
          eventTime: "11:00",
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          eventName: "Advanced Tap Classes",
          eventLocation: "London",
          eventDescription: "Train with world-famous instructor, develop techniques and learn new choreography.",
          skillLevel: "Advanced",
          CategoryId: 29,
          equipNeeded: "1",
          eventPrice: 10,
          eventDate: "2024-11-20",
          eventTime: "20:00",
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          eventName: "Jazz Dance Class",
          eventLocation: "Cardiff",
          eventDescription: "Learn a new skill! Relaxed beginners jazz dance classes - come solo or with a partner.",
          skillLevel: "Beginners",
          CategoryId: 29,
          equipNeeded: "0",
          eventPrice: 7,
          eventDate: "2024-11-19",
          eventTime: "20:00",
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          eventName: "Improv Group",
          eventLocation: "Manchester",
          eventDescription: "Develop your improv skills in an open and relaxed environment - all you need to bring is your imagination.",
          skillLevel: "All Levels",
          CategoryId: 29,
          equipNeeded: "0",
          eventPrice: 5,
          eventDate: "2024-10-19",
          eventTime: "18:00",
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          eventName: "Bird Watching",
          eventLocation: "London",
          eventDescription: "Discover incredible local wildlife living in your local park. We have spare binoculars if you don't have your own.",
          skillLevel: "All Levels",
          CategoryId: 30,
          equipNeeded: "0",
          eventPrice: 0,
          eventDate: "2024-10-12",
          eventTime: "09:00",
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          eventName: "Hedgehog House Making",
          eventLocation: "Cardiff",
          eventDescription: "Learn how to create a safe place of rest for our spikey little friends before they hibernate.",
          skillLevel: "All Levels",
          CategoryId: 30,
          equipNeeded: "0",
          eventPrice: 0,
          eventDate: "2024-10-22",
          eventTime: "11:00",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        
    ], 
    {});
  },

  async down (queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  }
};
